### PR TITLE
Posts

### PR DESCRIPTION
**Pull request by riverrun**
This PR adds posts - providing most of the functionality outlined in #577.

## Further details

Added:

* post routes
    * these are nested under user
    * the index and show routes are open to any user (including anonymous users), and all other routes can only be accessed by the owner of the post
* post tags

Still todo:

* twitter cards
* different capabilities for different levels of users (for example, new users can only write 140 chars)
* limiting posts to just followers (followers not implemented yet)

### CODE REVIEW

**Comment by wintermeyer** [comment]
Please don't implement `different capabilities for different levels of users (for example, new users can only write 140 chars)`. I'm not sure about this any more and we don't need it in the first 2.0 version. So no limits about the length of a post. OK. Maybe a very big limit just so that no-one can crash the DB.

**Comment by riverrun** [comment]
Ok. I will add a note to the issue.

For the body of each post, the current limit is set to 255 chars.

**Comment by wintermeyer** [comment]
> For the body of each post, the current limit is set to 255 chars.

That should be a lot more. More like 100,000 chars. Or is there a limitation on the DB side for such a big text? People should be able to post complete book chapters if they feel like it.

**Comment by riverrun** [comment]
Ok. Let me look into our options - how big we can / should be making it - and then I can update it.

One other I should have mentioned is that markdown is not yet supported.

**Comment by riverrun** [comment]
According to [this guide](https://blog.hubspot.com/marketing/character-count-guide), Facebook set a limit of 63,206 characters, and Linkedin set a limit of 40,000 characters for blog posts.

In our case, shall we make it around 50,000, 60,000, or more?

**Comment by wintermeyer** [comment]
> According to [this guide](https://blog.hubspot.com/marketing/character-count-guide), Facebook set a limit of 63,206 characters, and Linkedin set a limit of 40,000 characters for blog posts.
> 
> In our case, shall we make it around 50,000, 60,000, or more?

Let's make it 126,412 (double the amount of Facebook). No, forget that. Funny but doesn't make sense. Let's do 150,000 which is an easy to remember number and give plenty of room for everybody to write stories.

**Review by wintermeyer — APPROVED** [review]

**Pull request merged**
