### PR TITLE
Validate url

### PR DESCRIPTION
**Pull request by BrummbQ**
Ok, I've learned about the translation system and added german translations. mix.lock is also included now, forgot about that, sorry.

The ExMachina update is actually not random, but required for this test. Didn't have much luck with the old version. So I can't split it up, because the feature, test and upgrade are forming an unit.

Ignore the "push" commits. github just went down.

### CODE REVIEW

**Comment by wintermeyer** [comment]
Please fix the following merging conflicts and we should be good to go:
```
Auto-merging priv/gettext/en/LC_MESSAGES/default.po
CONFLICT (content): Merge conflict in priv/gettext/en/LC_MESSAGES/default.po
Auto-merging priv/gettext/default.pot
CONFLICT (content): Merge conflict in priv/gettext/default.pot
Auto-merging priv/gettext/de/LC_MESSAGES/default.po
CONFLICT (content): Merge conflict in priv/gettext/de/LC_MESSAGES/default.po
Auto-merging mix.exs
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by BrummbQ** [comment]
okay, all fixed!

**Comment by wintermeyer** [comment]
Nice work! Thank you. It's already live.

**Comment by wintermeyer** [comment]
BTW: You should add your Twitter account and a avatar to your vutuv profile. I just verified it.

**Pull request merged**
