### PR TITLE
Email schema, bamboo for development

### PR DESCRIPTION
**Pull request by hendri-tobing**
Pull request for #573 

Add the following:
* EmailAddress schema
* Bamboo Email for development
* Add, Edit Email

Some tests are skipped. Need to add sending-email-verification on new email later.

### CODE REVIEW

**Comment by wintermeyer** [comment]
@hendri-tobing Just making sure that you saw the conflicts. I'm now sure if GitHub sends an automated email in these cases. Does it?

**Comment by riverrun** [comment]
There are a few problems with the use of git in this pull request. We need to discuss that before proceeding further.

I am a bit tired now, and so I will look into how to solve those issues tomorrow.

**Comment by wintermeyer** [comment]
> There are a few problems with the use of git in this pull request. We need to discuss that before proceeding further.

@hendri-tobing Please do me a favor and make a backup of your code. Better save than sorry.

> I am a bit tired now, and so I will look into how to solve those issues tomorrow.

👍

**Comment by hendri-tobing** [comment]
If needed, I will cancel this pull request and create a new one. Thank you.

**Comment by hendri-tobing** [comment]
Git conflict issue.

**Comment by riverrun** [comment]
@hendri-tobing I am going to explain what the issues were and what you need to do before creating a new pull request.

First of all, when maintaining a fork of a project, it is important that you keep the master branch in sync with the upstream master branch. This is why you do not want to do any work on the master branch - you always want to open new branches (from the master branch) before doing any work. There is more information about this subject in the 'Pull requests' section of the CONTRIBUTING guide (if there is anything you do not understand in that guide, just let me know).

As for this situation, you need to first back up your work, then reset the master branch to be in sync with the upstream master, open a new branch, copy the work you did (from the backup), and then push the new branch and open a pull request from this new branch.

All the commands in this guide should be run from the vutuv root directory.

1. Backup your work

    ```
    mkdir ../vutuv_bak
    cp -r CONTRIBUTING.md priv lib test ../vutuv_bak
    ```

2. Reset the master branch of your fork

    ```
    git reset --hard 50a3095
    git pull upstream master
    git push --force origin master
    ```

3. Open a new branch and copy the backup of your work to this new branch

    ```
    git checkout -b email_addresses
    cp -r ../vutuv_bak/* .
    ```

4. Make sure all the tests pass

    ```
    mix test
    ```

5. Commit and push the changes

    ```
    git add .
    git commit -a -m 'Added email addresses context, table and routes'
    git push origin email_addresses
    ```

6. Open the pull request

If you have any questions, please let me know.

**Comment by hendri-tobing** [comment]
Thank you for a very informative and effective explanation. 👍

**Pull request closed without merging**
