### PR TITLE
Validate url

### PR DESCRIPTION
**Pull request by BrummbQ**
Hello again,

To prevent any gibberish url input, I tried to improve the validation. The model first parses the url and then checks the hostname, so this should be quite safe. To test the new check I implemented a test for the url controller and on the way also upgraded and used ex machina, which was working surprisingly pleasant.

### CODE REVIEW

**Comment by cjfreeze** [comment]
Thanks for taking the time to try out the app!

Firstly, I have a question, and I admit beforehand that I only glanced over the changes.
My question is: what was the purpose of the changes of in the templates?

Secondly, I see that you generated tests from ex machina for this. I've been looking into that for when we get to the milestone that addresses tests. For now though, we'd like to leave tests untouched... But feel free to separate them into another pull request.

**Comment by wintermeyer** [comment]
@cjfreeze The templates haven't changed. AFAIK they are just nicer intended.

**Comment by wintermeyer** [comment]
I haven't tested it yet but I like it so far. I'll give it a try tomorrow.

**Comment by wintermeyer** [comment]
But I would have liked it to be two PRs.

**Comment by cjfreeze** [comment]
Ah just cleaned the templates then. Yeah that does need to be done in several areas.

**Comment by wintermeyer** [comment]
I checked the Pull-Request and I appreciate the effort. Thank you!

Please resolve the following issues:
- `can't resolve url` needs to be translated into the German `die URL kann vom Nameserver nicht aufgelöst werden` (please contact us in case you don't know how to do I18n work)
- The correct `mix.lock` is missing. We can not deploy without the correct version.
- Please split up the PR into two. One for the ex_machina upgrade and one for the url validation.

**Comment by wintermeyer** [comment]
https://github.com/vutuv/vutuv/blob/master/faster_pr_reviews.md

**Pull request closed without merging**
